#!/bin/sh

# Author: Gustaf Franzen <gustaffranzen@icloud.com>

mount -t proc none /proc
mount -t sysfs none /sys

echo "[init] Booted Linux" > /dev/ttyAMA1

insmod /rtcore.ko

busybox mknod /dev/rtcore c 510 0
cat /sys/module/rtcore/sections/.text
exec /bin/sh
