
// Author: Gustaf Franzen <gustaffranzen@icloud.com>
#ifndef _MEMORY_LAYOUT_H_
#define _MEMORY_LAYOUT_H_

#include "rtcore.h"

#define TOJRT_RING_ADDR (JRT_MEM_PHYS)
#define JRT_STACK_START (JRT_MEM_PHYS + JRT_MEM_SIZE)
#define JRT_HEAP_START ((JRT_MEM_PHYS + sizeof(struct mpsc_ring) + 15) & ~((uintptr_t)15))

#define TOJRT_RING_SIZE ((JRT_HEAP_START - TOJRT_RING_ADDR) - 1)

#ifdef AUTOGEN_HEADER
#include <stdio.h>
#include <string.h>
int main(void)
{
	int i;
	char *fn;
	char guard[4096];
	char *dot;

	fn = strdup(__FILE__);
	dot = strchr(fn,'.');
	if (dot)
		*dot = '_';
	snprintf(guard, 4096, "_AUTOGEN_%s_", fn);

	printf("// autogenerated header from file %s\n", __FILE__);
	printf("#ifndef %s\n", guard);
	printf("#define %s\n\n", guard);

	printf("#define TOJRT_RING_ADDR (0x%llx)\n", TOJRT_RING_ADDR);
	printf("#define JRT_STACK_START (0x%llx)\n", JRT_STACK_START);
	printf("#define TOJRT_RING_SIZE (0x%llx)\n", TOJRT_RING_SIZE);

	printf("\n#endif /* %s */\n", guard);
}
#endif

#endif
